SistemaVendas/Models/CategoriaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaVendas.Models
{
    public class CategoriaViewModel
    {
        public int? Codigo { get; set; }
        [Required(ErrorMessage ="informe a Descrição da Categoria") ]
        public string Descricao { get; set; }
    }
}

SistemaVendas/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaVendas.DAL;
using SistemaVendas.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SistemaVendas.Models;
using Microsoft.EntityFrameworkCore;

namespace SistemaVendas.Controllers
{
    public class CategoriaController : Controller
    {
        protected ApplicationDbContext _Context;
        public CategoriaController(ApplicationDbContext context)
        {
            _Context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Categoria> lista = _Context.Categoria.ToList();
            _Context.Dispose();
            return View(lista);
        }

        [HttpGet]
        public IActionResult Cadastro(int? id)
        {
            CategoriaViewModel viewModel = new CategoriaViewModel();
            if (id != null)
            {
                var entidade = _Context.Categoria.Where(x => x.Codigo == id).FirstOrDefault();
                viewModel.Codigo = entidade.Codigo;
                viewModel.Descricao = entidade.Descricao;
            }
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Cadastro(CategoriaViewModel entidade)
        {
            if (ModelState.IsValid)
            {
                Categoria objCategoria = new Categoria()
                {
                  
                    Codigo = entidade.Codigo,
                    Descricao = entidade.Descricao
                };

                if(entidade.Codigo == null)
                {
                    _Context.Categoria.Add(objCategoria);
                }
                else
                {
                    _Context.Entry(objCategoria).State = EntityState.Modified;
                }

                _Context.SaveChanges();
            }
            else
            {
                return View(entidade);
            }

            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Excluir(int id)
        {
            var ent = new Categoria() { Codigo = id };
            _Context.Attach(ent);
            _Context.Remove(ent);
            _Context.SaveChanges();
            return RedirectToAction("index");
        }

    }
}

SistemaVendas/Views/Categoria/Cadastro.cshtml
@{
    ViewData["Title"] = "Categorias";
}

<h2>Categorias</h2>
<hr />

@model SistemaVendas.Models.CategoriaViewModel

@{
    var disable = (Model.Codigo == null) ? "disabled" : string.Empty;
}

<form asp-controller="Categoria" asp-action="Cadastro" method="post">
    <input type="hidden" asp-for="Codigo" value="@Model.Codigo" />

    <div class="form-group">
        <div class="col-4">
            <label>Descrição</label>
            <input asp-for="Descricao" type="text" value="@Model.Descricao" class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
        <br />
        <div class="col">
            <button type="button" class="btn btn-info" onclick="Novo()">Novo</button>
            <button type="submit" class="btn btn-success">Gravar</button>
            <button type="button" class="btn btn-warning" onclick="Listagem()">Listagem</button>
            <button type="button" class="btn btn-danger" onclick="Excluir(@Model.Codigo)" @disable>Excluir</button>
        </div>

    </div>

</form>
<script>
    function Novo() {
        Request("Cadastro");
    }
    function Listagem() {
        Request("");
    }
    function Excluir(Codigo) {
        Request("Excluir\\" + Codigo);
    }
    function Request(request) {
        window.location = window.origin + "\\Categoria\\" + request;
    }
</script>

SistemaVendas/Views/Categoria/Index.cshtml
@{
    ViewData["Title"] = "Categorias";
}

@model List<SistemaVendas.Entity.Categoria>;

<h2>Categorias</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr style="background-color:#f6f6f6">
            <th>Código</th>
            <th>Descrição</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="Editar(@item.Codigo)" style="cursor:pointer;">
                <td>@item.Codigo</td>
                <td>@item.Descricao</td>
            </tr>
        }

    </tbody>
</table>
<br />
<button type="button" class="btn btn-block btn-primary" onclick="Cadastrar()">Cadastro Categoria</button>
<script>
    function Editar(Codigo) {
        window.location = window.origin + "\\Categoria\\Cadastro\\" + Codigo;
    }
    function Cadastrar() {
        window.location = window.origin + "\\Categoria\\Cadastro";
    }
</script>